server:
  port: 8080

#------------------------------------------------------------热部署
#debug: true
spring:
  #  devtools:
  #    restart:
  #      enabled: true  #设置开启热部署
  #  freemarker:
  #    cache: false    #页面不加载缓存，修改即时生效
#------------------------------------------------------------热部署

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.211.55.30:3306/check_duplicate?useUnicode=true&characterEncoding=UTF-8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql=true:
  servlet: #上传文件
    multipart:
      max-file-size: 32MB #单个文件大小限制
      max-request-size: 128MB #一次上传文件大小限制
  redis:
    host: 10.211.55.30
    port: 6379

#开启knife4j增强
knife4j:
  enable: true

